version: '2'
services:
  moos-app:
    build: ./php-5.6-apache
    container_name: moos-app
    working_dir: /var/www/html/cakephp
    expose:
      - "9000"
    ports:
      - '80:80'
    volumes:
      - ./cake:/var/www/html/
    links:
      - moos.local.dev
    environment:
      PHP_XDEBUG_ENABLED: 1 # Set 1 to enable.
      XDEBUG_CONFIG: remote_host=10.254.254.254
    tty: true
  moos.local.dev:
    image: 'mysql:5.5'
    hostname: 'moos.local.dev'
    container_name: 'moos.local.dev'
    ports:
      - "3306:3306"
    command: mysqld --character-set-server=utf8
    environment:
      MYSQL_HOST: 'moos.local.dev'
      MYSQL_DATABASE: 'moos'
      MYSQL_USER: 'root'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - mysql-data:/var/lib/mysql
volumes:
  mysql-data:
    driver: local
