version: '2'
services:
  moos-app:
    build:
        context: ./
        dockerfile: ./php-apache/Dockerfile
    container_name: "moos-app${port}"
    working_dir: /var/www/html/cakephp
    ports:
      - '${port}:80'
    links:
      - moos.local.dev
    environment:
      PHP_XDEBUG_ENABLED: 1 # Set 1 to enable.
      XDEBUG_CONFIG: remote_host=10.254.254.254
    tty: true
  moos.local.dev:
    build:
        context: ./sql/
    hostname: 'moos.local.dev'
    container_name: 'moos.local.dev${port}'
    working_dir: /
    command: mysqld --character-set-server=utf8
    environment:
      MYSQL_HOST: 'moos.local.dev'
      MYSQL_DATABASE: 'moos'
      MYSQL_USER: 'root'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - mysql-data:/var/lib/mysql
      - ./sql/:/docker-entrypoint-initdb.d/data.sql
volumes:
  mysql-data:
    driver: local
